export const TAGS_TABLE_COORDINATES = {
  COLUMN_ONE: 0.29427083333,
  COLUMN_TWO: 0.42395833333,
  COLUMN_THREE: 0.55416666666,
  ROW_ONE: 0.509,
  ROW_TWO: 0.60462962963
}

export const TAGS_DIMENSIONS = {
  WIDTH: 0.12,
  HEIGHT: 0.07
}

export const TAGS = [
  { x: TAGS_TABLE_COORDINATES.COLUMN_ONE, y: TAGS_TABLE_COORDINATES.ROW_ONE },
  { x: TAGS_TABLE_COORDINATES.COLUMN_TWO, y: TAGS_TABLE_COORDINATES.ROW_ONE },
  {
    x: TAGS_TABLE_COORDINATES.COLUMN_THREE,
    y: TAGS_TABLE_COORDINATES.ROW_ONE
  },
  { x: TAGS_TABLE_COORDINATES.COLUMN_ONE, y: TAGS_TABLE_COORDINATES.ROW_TWO },
  { x: TAGS_TABLE_COORDINATES.COLUMN_TWO, y: TAGS_TABLE_COORDINATES.ROW_TWO }
]
